### PR TITLE
Added support for WordPress 5.0 and implemented DB upgrade flow.

### PR DESCRIPTION
**Pull request by mohsinrasool**
Gutenberg support added and first underscore removed from the meta key due to non-compliant with Gutenberg meta key support.

### CODE REVIEW

**Comment by MillerMedia** [comment]
Thanks @mohsinrasool this is great (and long overdue for us!). I will review shortly and run some tests.

**Comment by mohsinrasool** [comment]
@MillerMedia Have got some time to look at it?

**Comment by MillerMedia** [comment]
Hi @mohsinrasool not yet. Sorry about that, we've had a bit of chaotic couple of weeks here in the office but I do have this queued up for the team and should be able to get to it very soon. Thanks!

**Comment by mm-stuart** [comment]
@mohsinrasool looks good and works well on Gutenberg. Thank you!

A few tweaks are needed for the backwards compatibility, I shall work on that before creating a new version

**Comment by MillerMedia** [comment]
@mohsinrasool Your changes (along with our updates) has gone live, thanks for the help on this! Do you have a Wordpress.com username? We can add you as a contributor on the plugin if so. Thanks!

**Comment by mohsinrasool** [comment]
@MillerMedia Thanks man! My WP username is the same mohsinrasool.

**Pull request merged**
